# Generated by Django 5.0.6 on 2024-07-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartelera', '0007_delete_obrasala'),
        ('utileria', '0003_alter_obrateatro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('obra_teatro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras_salas', to='utileria.obrateatro')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_salas', to='cartelera.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_peliculas', to='utileria.sala')),
            ],
        ),
    ]
