# Generated by Django 5.0.6 on 2024-07-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorObra',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('anos_experiencia', models.IntegerField()),
            ],
            options={
                'db_table': 'directoreobras',
            },
        ),
        migrations.CreateModel(
            name='Escenografo',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('anios_experiencia', models.IntegerField()),
            ],
            options={
                'db_table': 'escenografos',
            },
        ),
        migrations.CreateModel(
            name='ObrasTeatro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'obrasteatro',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='Utileria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'utileria',
            },
        ),
        migrations.CreateModel(
            name='ReservaUtileria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('director_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utileria.directorobra')),
                ('obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utileria.obrasteatro')),
                ('utileria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utileria.utileria')),
            ],
            options={
                'db_table': 'reservasutileria',
            },
        ),
        migrations.AddField(
            model_name='obrasteatro',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utileria.salas'),
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escenografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utileria.escenografo')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utileria.reservautileria')),
            ],
            options={
                'db_table': 'supervisiones',
            },
        ),
    ]
