# Generated by Django 5.0.6 on 2024-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utileria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrateatro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obrateatro/imagen/'),
        ),
    ]
