# Generated by Django 5.0.6 on 2024-07-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utileria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorobra',
            name='id',
        ),
        migrations.AlterField(
            model_name='directorobra',
            name='usuario_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
