# Generated by Django 5.0.6 on 2024-07-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Invitado', max_length=50),
        ),
    ]
