# Generated by Django 5.0.6 on 2024-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
