# Generated by Django 5.0.6 on 2024-07-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Director_Obra', 'Director de Obra'), ('Escenografo', 'Escenógrafo'), ('Informatico', 'Informático'), ('Utilero', 'Utilero'), ('Usuario', 'Usuario')], default='Usuario', max_length=50),
        ),
    ]
