# Generated by Django 5.0.6 on 2024-07-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utileria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('realizador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('obra_teatro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras_salas', to='utileria.obrateatro')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_peliculas', to='utileria.sala')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_salas', to='cartelera.pelicula')),
            ],
        ),
    ]
