# Generated by Django 5.0.6 on 2024-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
    ]
